name: build

on: push

jobs:
  build:
    strategy:
      matrix:
        platform:
          - runner: ubuntu-24.04
            arch: x86_64
          - runner: ubuntu-24.04-arm
            arch: arm64
        python:
          - 3.12
          - 3.13
          - 3.14
    runs-on: ${{ matrix.platform.runner }}
    container: public.ecr.aws/lambda/python:${{ matrix.python }}
    steps:
      - run: pip install -t image/python simple-salesforce
      - uses: actions/upload-artifact@v7
        with:
          name: simple-salesforce-py${{ matrix.python }}-${{ matrix.platform.arch }}
          path: image
