name: build

on: push

jobs:
  build:
    strategy:
      matrix:
        platform:
          - runner: ubuntu-24.04
            arch: x86_64
          - runner: ubuntu-24.04-arm
            arch: arm64
        python:
          - 3.12
          - 3.13
          - 3.14
        package:
          - simple-salesforce-1.12.10
    runs-on: ${{ matrix.platform.runner }}
    container: public.ecr.aws/lambda/python:${{ matrix.python }}
    steps:
      - run: pip install -t image/python ${{ package }}
      - uses: actions/upload-artifact@v7
        with:
          name: ${{ package }}-${py${{ matrix.python }}-${{ matrix.platform.arch }}
          path: image
