name: Build layer

on: push

jobs:
  default:
    runs-on: ubuntu-24.04-arm
    container:
      image: public.ecr.aws/lambda/python:3.13
    steps:
      - run: pip install -t python simple-salesforce
      - run: dnf -y install zip
      - run: zip -r layer.zip python
